# Ayudantía 5 — (Ejercicios)

In [1]:
import pandas as pd
from datetime import datetime

## Ejercicio 1 — Normalización de nombres y correos
**Dataset:**

In [2]:
df1 = pd.DataFrame({
    'id': ['01',' 02 ','003'],
    'nombre_completo': [' ana GÓMEZ  ', 'LUIS   pérez', 'soFÍA   díAz '],
    'emails': ['ana@uc.cl; ANA@GMAIL.COM', 'l.perez@uc.cl', 'sdiaz@mail.com; sofia@uc.cl']
})
df1

     id nombre_completo                       emails
0    01     ana GÓMEZ       ana@uc.cl; ANA@GMAIL.COM
1   02     LUIS   pérez                l.perez@uc.cl
2   003   soFÍA   díAz   sdiaz@mail.com; sofia@uc.cl

**Tareas:**
1) Deja `nombre_completo` en *Title Case* sin espacios extra.

2) Convierte correos a minúsculas, elimina espacios internos y separa múltiples correos en **filas** (`explode`).

3) Normaliza `id` a tipo entero (`Int64`), quitando espacios y ceros a la izquierda.

> Deja tu solución en el DataFrame `res1`.

In [37]:
# TU CÓDIGO AQUÍ
res1 = df1.copy()
# ... tu solución ...
res1['nombre_completo'] = (
    res1['nombre_completo']
    .str.strip()
    .str.title()
    .str.replace(r'\s+', ' ', regex=True)
)

res1['emails_lista'] = (res1['emails'].str.split(";"))

res1 = res1.drop(columns='emails')
res1 = res1.explode('emails_lista', ignore_index=True)
res1 = res1.rename(columns={'emails_lista':'email'})

res1['id'] = (
    res1['id'].str.strip()
    .str.replace(r'^0+', '', regex=True)
    .replace('', None)
    .astype('Int64')
    )

res1

   id nombre_completo           email
0   1       Ana Gómez       ana@uc.cl
1   1       Ana Gómez   ANA@GMAIL.COM
2   2      Luis Pérez   l.perez@uc.cl
3   3      Sofía Díaz  sdiaz@mail.com
4   3      Sofía Díaz     sofia@uc.cl

## Ejercicio 2 — Limpieza de montos
**Dataset (mismos separadores para simplificar):**

In [4]:
df2 = pd.DataFrame({
    'monto': ['10.000', '12.500', '3.000', '4.500']
})
df2

    monto
0  10.000
1  12.500
2   3.000
3   4.500

**Tareas:**
1) Interpreta `'.'` como separador de **miles** y deja el separador decimal como `.`.

2) Convierte a `float`.

3) El DataFrame resultante debe quedar como en la columna `monto_float`.

> Deja tu solución en el DataFrame `res2` con una columna `monto_float`.

In [43]:
# TU CÓDIGO AQUÍ
res2 = df2.copy()
# ... tu solución ...
res2['monto_float'] = (
    res2['monto'].str.replace('.', '')
    .astype('float64')
    )

res2

    monto  monto_float
0  10.000      10000.0
1  12.500      12500.0
2   3.000       3000.0
3   4.500       4500.0

## Ejercicio 3 — Fechas en mismo formato
**Dataset (todas en formato `'%d/%m/%Y'`):**

In [6]:
df3 = pd.DataFrame({
    'fecha': ['12/03/2024','10/05/2024','15/06/2024','01/12/2024']
})
df3

        fecha
0  12/03/2024
1  10/05/2024
2  15/06/2024
3  01/12/2024

**Tareas:**
1) Convierte `fecha` a `datetime` usando `to_datetime` con `format='%d/%m/%Y'` y `errors='coerce'`.

2) Devuelve la columna `fecha` **como string** en formato `YYYY-MM-DD` (`dt.strftime`).

3) Por último extrae agregue las siguientes nuevas columnas:
* `year` con únicamente el año
* `month-day` con el mes y dia fecha en formato MM-DD

> Deja tu solución en el DataFrame `res3`.

In [55]:
# TU CÓDIGO AQUÍ
res3 = df3.copy()
# ... tu solución ...}
res3['fecha'] = pd.to_datetime(res3['fecha'], format='%d/%m/%Y', errors='coerce')
res3['fecha'] = res3['fecha'].dt.strftime('%Y/%m/%d')
res3[['year', 'month', 'day']] = res3['fecha'].str.split('/', expand=True)
res3['month-day'] = res3['month'] + '/' + res3['day']
res3.drop(columns=['month', 'day'])

        fecha  year month-day
0  2024/03/12  2024     03/12
1  2024/05/10  2024     05/10
2  2024/06/15  2024     06/15
3  2024/12/01  2024     12/01

## Ejercicio 4 — Extracción con `str.split` y `explode`
**Dataset:** `región|comuna` en una columna, múltiples hobbies separados por `;`.

In [8]:
df4 = pd.DataFrame({
    'id': [1,2,3],
    'region_comuna': ['RM|Santiago', 'V|Viña del Mar', 'VIII|Concepción'],
    'hobbies': ['futbol;leer', 'cine', 'musica;ajedrez;gaming']
})
df4

   id    region_comuna                hobbies
0   1      RM|Santiago            futbol;leer
1   2   V|Viña del Mar                   cine
2   3  VIII|Concepción  musica;ajedrez;gaming

**Tareas:**
1) Separa `region_comuna` en `region` y `comuna`.

2) Convierte `hobbies` en filas (`explode`).

3) Mantén `id`, `region`, `comuna`, `hobbies`.

> Deja tu solución en el DataFrame `res4`.

In [78]:
# TU CÓDIGO AQUÍ
res4 = df4.copy()
# ... tu solución ...
col_idx = res4.columns.get_loc('region_comuna')
res4[['region', 'comuna']] = res4['region_comuna'].str.split('|', expand=True)
res4.insert(col_idx, 'region', res4.pop('region'))
res4.insert(col_idx + 1, 'comuna', res4.pop('comuna'))
res4 = res4.drop(columns='region_comuna')
res4['hobbies_ex'] = res4['hobbies'].str.split(';')
res4 = res4.drop(columns='hobbies')
res4 = res4.explode('hobbies_ex', ignore_index=True)
res4 = res4.rename(columns={'hobbies_ex':'hobbies'})
res4

   id region        comuna  hobbies
0   1     RM      Santiago   futbol
1   1     RM      Santiago     leer
2   2      V  Viña del Mar     cine
3   3   VIII    Concepción   musica
4   3   VIII    Concepción  ajedrez
5   3   VIII    Concepción   gaming

## Ejercicio 5 — Conexión de DataFrames y cardinalidad
**Dataset:**

In [10]:
alumnos = pd.DataFrame({'id':[1,2,3], 'nombre':['Ana','Luis','Sofía']})
notas   = pd.DataFrame({'id':[1,2,4], 'nota':[6.5,5.8,7.0]})
emails  = pd.DataFrame({'id':[1,1,2], 'email':['ana@a.com','ana@b.com','luis@c.com']})
print('ALUMNOS:')
display(alumnos)
print('\nNOTAS:')
display(notas)
print('\nEMAILS:')
display(emails)

ALUMNOS:

   id nombre
0   1    Ana
1   2   Luis
2   3  Sofía

NOTAS:

   id  nota
0   1   6.5
1   2   5.8
2   4   7.0

EMAILS:

   id       email
0   1   ana@a.com
1   1   ana@b.com
2   2  luis@c.com

**Tareas:**
1) `merge` **inner** entre `alumnos` y `notas` (¿cuántos quedan?).

2) `merge` **left** entre `alumnos` y `emails` (¿qué cardinalidad se observa?).

3) Explica en una celda Markdown por qué aparecen duplicados en el punto (2) si los hay.

> Deja tus resultados en `res5_inner` y `res5_left`. La explicación va en Markdown debajo.

In [79]:
# TU CÓDIGO AQUÍ

#res5_inner = pd.merge(alumnos, notas, on="columna", how='tipo')
#res5_left = pd.merge(alumnos, emails, on='columna', how='tipo')
res5_inner = pd.merge(alumnos, notas, on='id', how='inner')
res5_left = pd.merge(alumnos, emails, on='id', how='left')
print('INNER:')
display(res5_inner)
print('\nLEFT:')
display(res5_left)

INNER:

   id nombre  nota
0   1    Ana   6.5
1   2   Luis   5.8

LEFT:

   id nombre       email
0   1    Ana   ana@a.com
1   1    Ana   ana@b.com
2   2   Luis  luis@c.com
3   3  Sofía         NaN

**Explicación (tu texto aquí):**

- ...